---
- name: Configure HCP Terraform agent host
  hosts: agent
  become: true

  pre_tasks:
    - name: Load SOPS-encrypted variables
      community.sops.load_vars:
        file: "{{ playbook_dir }}/group_vars/all.yml"

  roles:
    - role: docker
    - role: tfc-agent
