#ENC[AES256_GCM,data:k+Fhoksf/x3nWngKr9S5,iv:pHLlP+j13Yce8axW4CCjUmhm+SohQs+45T58GeQFcD4=,tag:Bl2ZaXfywbcOkPYHQasxfQ==,type:comment]
#ENC[AES256_GCM,data:e7HDVqIsJF3svlXjDOyonJmRdO/fc3eshUOpXD74U20=,iv:sMQD8N2l3D7qupk0xS8oXIG355H1XvetQIAHb7fhQgU=,tag:rxZcLafMT6EfHjxg0KYpBQ==,type:comment]
#ENC[AES256_GCM,data:XxlH/46mmsqW7X3xsyl7UCSPG3HEjPW2gRJmisF6yMI=,iv:GFj1JcsKqIe2Or0baqTBwPawKau70KO8Cmy794gnff8=,tag:Zq07r81Pz570Nk1pIoB6Pw==,type:comment]
#ENC[AES256_GCM,data:24Xcw+UaG5lx0mRTFz9yvLB0wIPBRv136BPHQGEyMMwuhzRKfN45ZUHgCQF1LFHRmNNkaTChr9GPItXXmCB05wAb4zfAm9g=,iv:N8VcdM1Pw8Q+NA+460EZfmr1XTvsHfab9es6J0eu5AY=,tag:AuRpyc4RUz+jQbk5QqLXyQ==,type:comment]
#ENC[AES256_GCM,data:OW4VgHM5qFShvJXy2/6SAQ4J5nagBB2pyFe+0TYayKplYXPfOSgrILMoFS0Tv2+Z2AVAX3SGX8s7zSShUN7uV8u54Lzf1olaM2iL,iv:ImZC39YREPzinb//4DQ48/+RQlChEULV2IQgFDPoavM=,tag:ccJHFxN9wDEjQqXniMAvRQ==,type:comment]
#
#ENC[AES256_GCM,data:dZ+M/ijeAt3HiF78EUy5kcraih6K7biOSYCCtqwaa58OP2IflbDkbbSxH6/vvTjTZDeSNOYMa5T14IsmNZVNr6hMLaOJTw==,iv:28Bo2cyC1DEjw3EnELGQzPw2FzYhdkjnDmR+umj8NbE=,tag:OI227q0FqSX9USDGM/eYmw==,type:comment]
#ENC[AES256_GCM,data:ULZffmM+f6T5/8GA9LUZR3WDBjzjkZmNTjx6bhpABc09DKdbwlmoKj+c/6cUnguKqterYUB8ddHhk+82FNm1w/x4yPyTVvo1xAhcJ4nRhf6j9hsNImc9,iv:+IRVzcejkgzETAcD56x0bc5JHX5eC6N9i6PoBNC2e/4=,tag:PNeRhjRUoBJIypbQJ84z1g==,type:comment]
#ENC[AES256_GCM,data:RcdS6sQ/sxN17HCQ4eOufdGeYA/6AG8U2g==,iv:DZ2R26V+i7hXI7B6aNtWNlkj61Ci9g4SggLnG/5Tc3M=,tag:J3f5ijMdCwny6Nzz2XNaww==,type:comment]
nextcloud_admin_user: ENC[AES256_GCM,data:HsfB7m0=,iv:qH8wsdpX3yISLdjYsWSnRFtXiL/Y/hWWHd1sILd7CYU=,tag:NUtDXnP5iXLw9u2f56ARmA==,type:str]
nextcloud_admin_password: ENC[AES256_GCM,data:HiWDhby6c2w=,iv:NcjbVhLsZ9cl68+TMMbaEaI6iCrNKUzMQigM7R/ZpWI=,tag:2V22TiwVUf+a2hh9rH2Qjg==,type:str]
nextcloud_db_host: ENC[AES256_GCM,data:eL4Ud6pcrbAUvuVU,iv:l/xt0c+DOGbPWkJ2DXZCRGygxnuAytIMq2OozTaeiG0=,tag:0ZSvmHLs6j+Vk1168M5HTg==,type:str]
nextcloud_db_name: ENC[AES256_GCM,data:cYrTytbn9YvU,iv:TyCcpGZd1qBcsM0KK14x6QgrFZOjgajSyROohRbar7Q=,tag:6tciPy5hRCMokYE8e7v0ag==,type:str]
nextcloud_db_user: ENC[AES256_GCM,data:S4tBu6EIhCEn,iv:vWdi8f5pEYcfXVjG3DkPGHpCYMOQo7b0b6fEHirY67U=,tag:BqTvyYn54xQqlg0gU2Wd4g==,type:str]
nextcloud_db_password: ENC[AES256_GCM,data:+OM4R+9lY6M=,iv:YsDuddxa2ZZbY7LLqspznsw0TW8vos4tDRynDe/2q+c=,tag:nwBq2KlQBgnSc7UniCODJg==,type:str]
nextcloud_data_dir: ENC[AES256_GCM,data:4ckaSn9oyRZHaNPW1VT1numPgAlQZiyCnmg=,iv:CbdvZ8PFZtwJGOvVOXTns1AhZ9VZiOj503Yzj9Ef6BI=,tag:FKTBN/1PL+2aaFbeWXLcYw==,type:str]
nextcloud_port: ENC[AES256_GCM,data:7WJZRQ==,iv:vo/ww8OtMpacIrHhVmWCXU37L/xL1Tq4wXEYoOskBvQ=,tag:YYNOmXT6dY3btj3+DOaJUQ==,type:int]
sops:
    age:
        - recipient: age12ftfkjfq9pdfk0h986sm9m3fgqy23mt5pf9hqda8tqjn3tvjyszs8h8kx9
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBFUkhEckNXL0dndS9Oa1BR
            V1FyZUd6OVQ1RWtwb2FJeXoxVHI1S2o3K2lFCkxBUTIra0VQWnkyMFk0cVE0M09D
            ZktDczY3SEtESDY1YnMzaFNFbjZYc2sKLS0tIGd4Q3RoUTJ6YmE0Z2hPdzdyN0tN
            bk9QanU0SWpLWGVRZ3Y0aWxpM1BpWHcKp5iD3zelDApsg+Q3wGq2H+/zSjXpGhQt
            IseAytx8BRRS2ARVmWxlJ7sGluQV7cfiRWSPsiKE4OmSfLtunB2/5g==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-29T02:55:18Z"
    mac: ENC[AES256_GCM,data:x+jTkDlXLJYdjzyaCfVSxlOYL/UpvrMR2DqTQSVnlk3FWL6iDeKQBobY0ZHhv7soSP1mamYXfX43tzdkvJ61gVOb0FKPkTm9bBFRuzjl3hStu2CVrC9hmmQnPk4nyahqEzqYvShI/9RvQQM30bIO2fUVfnvhvsWc432J02BgOzc=,iv:JSv6A+QxMDk2qMN2zAbkAYylb6GowuHBzhaqfO9Dfj4=,tag:CFqq8TFzcse53LG7+Ibzlg==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.12.2
